def_int_(self):
   pass
def par(self):

    numero  = 4
    rec = numero % 2
    if rec ==0:
        print("{} es par".format(numero))
    else:
        print("{} es impar". format(numero))

             problema: par
entrada     proceso                    salida
   numero calculo divisible 2      par  o impar
4            4 % 2 = 0
5            5/2   = 1
8
            rec = numero%2
            si rec = 0
               escribir "par"
            sino
              escibrir "Impar"
num
   4 / 2
 rec (0)2 coc
