   class logica:
       def_init_(self):
       pass

   def par (self, numero):
      rec  =  numero % 2
       return rec
            print("{} es par ".format(numero))

    ejer = logica()
    num = numero = int(imput("ingrese Numero:"))
    numeros = [1,3,8,4,5,10]
    pares = []
    for num in numeros:
        resp = ejer.par(num)
        if rsp == 0:
            pares.append(num)
    ejer.par(num)
